spring:
  application:
    name: sm-team-finder

logging:
  level:
    org.springframework: ERROR
    root: ERROR

api:
  apiUrl: https://<Enter base URL here>/
  getCardDetails: cards/get_details
  settings: settings
  playersLeaderboard: players/leaderboard
  findCards: /cards/find?ids=%s
  getUpcomingTournaments: tournaments/upcoming
  getUpcomingTournamentsUser: tournaments/upcoming?username=%s
  getInprogressTournaments: tournaments/in_progress
  getInprogressTournamentsUser: tournaments/in_progress?username=%s
  getCompletedTournaments: tournaments/completed
  getCompletedTournamentsUser: tournaments/completed?username=%s
  getTournament: tournaments/find?id=%s&token=%s&username=%s
  getCollection: cards/collection/%s
  getPlayerDetails: players/details?name=%s
  getPlayerQuests: players/quests?username=%s
  getCardStats: cards/stats
  getBattleHistory: battle/history?player=%s
  getBattleResult: battle/result?id=%s
  getBattleStatus: battle/status?id=%s

  safetyCheckUrl: http://localhost:7071/api/safetyCheck

newTeamListService: http://localhost:7071/api/toprated

time-delay-configuration:
  defaultDelay: 600
  delays:
    - account-name-one: 120
    - account-name-two: 120

defaults:
  similarTeamCountPermutation: 200
  similarTeamCountTeams: 30
  limitResultCount: 3
  topHandCount: 400
  bottomHandCount: 100
  maxAllotedTimeForRequest: 110
  delaySubmission: false
  teamsUrl: <URL that should return a collection of teams>
  bottomTeamsUrl: <URL that should return a collection of teams>
  battlesPerMatchup: 5
  questComparisonThreshold: .85
  threadsForSimulations: 2
  safetyLevel: 800
  safetyTime: 2000

  permission:
    maxRating: 10000

  cardReplacementOptions:
    5:
      - 167
      - 56
      - 200
    167:
      - 5
      - 56
      - 200
    16:
      - 178
      - 56
      - 200
    178:
      - 16
      - 56
      - 200
    27:
      - 189
      - 56
      - 200
    189:
      - 27
      - 56
      - 200
    38:
      - 156
      - 56
      - 200
    156:
      - 38
      - 56
      - 200
  alwaysAllowPermission:
    - always-allow-me
    - always-allow-me-too
  useMaxTimeAgainst:
    - delay-this-guy
    - delay-this-guy-too
  safetyCheck:
    - play-when-determined-safe
  rankedYieldListActive: true
  rankedYieldList:
    - always-win-when-to-another-in-this-list
    - second-priority
    - third-priority
    - fourth-priority
    - always-loose-to-another-in-this-list
  tournamentYieldListActive: true
  tournamentYieldList:
    - always-win-when-to-another-in-this-list
    - second-priority
    - third-priority
    - fourth-priority
    - always-loose-to-another-in-this-list
  recentCardWins:
    1: 69
    2: 17
    3: 56
    4: 5
    5: 23
    6: 46
    7: 11
    8: 61
    9: 17
    10: 19
    11: 37
    12: 8
    13: 44
    14: 219
    15: 4
    16: 61
    17: 69
    18: 23
    19: 3
    20: 27
    21: 70
    22: 3
    23: 32
    24: 44
    25: 2
    26: 3
    27: 40
    28: 109
    29: 40
    30: 2
    31: 32
    32: 170
    33: 145
    34: 37
    35: 76
    36: 23
    37: 4
    38: 58
    39: 14
    40: 37
    42: 26
    43: 4
    44: 58
    45: 4
    46: 1
    47: 12
    48: 2
    49: 10
    50: 7
    51: 15
    52: 100
    55: 29
    56: 123
    57: 32
    58: 10
    59: 110
    60: 46
    61: 1
    62: 106
    63: 62
    64: 136
    65: 27
    66: 56
    67: 13
    68: 29
    69: 24
    70: 10
    71: 41
    72: 35
    73: 14
    74: 33
    77: 14
    79: 10
    82: 323
    83: 72
    84: 14
    85: 25
    87: 29
    88: 31
    89: 8
    90: 34
    91: 151
    92: 7
    93: 49
    95: 81
    96: 3
    97: 8
    98: 113
    99: 40
    100: 12
    101: 47
    102: 83
    103: 10
    104: 132
    106: 33
    107: 40
    108: 18
    109: 53
    110: 85
    111: 143
    112: 149
    113: 67
    114: 1
    116: 54
    117: 18
    118: 53
    119: 46
    120: 41
    121: 1
    122: 64
    123: 110
    124: 13
    125: 38
    127: 4
    128: 22
    129: 44
    130: 95
    131: 300
    132: 17
    133: 14
    134: 33
    135: 2
    136: 93
    137: 7
    138: 8
    139: 2
    140: 4
    141: 92
    142: 3
    143: 88
    144: 16
    145: 11
    146: 35
    147: 5
    148: 24
    149: 14
    150: 32
    151: 14
    152: 52
    153: 12
    154: 1
    155: 6
    156: 10
    157: 8
    158: 74
    159: 9
    160: 14
    161: 7
    162: 26
    163: 30
    164: 1
    166: 28
    167: 33
    168: 18
    169: 108
    170: 4
    171: 3
    172: 116
    173: 8
    174: 2
    175: 22
    176: 2
    177: 57
    178: 23
    179: 38
    180: 176
    181: 9
    182: 27
    183: 135
    184: 16
    185: 98
    186: 63
    187: 19
    188: 17
    189: 56
    190: 8
    191: 32
    192: 20
    193: 53
    194: 58
    195: 12
    196: 86
    197: 39
    198: 55
    199: 55
    200: 50
    201: 20
    202: 43
    203: 67
    205: 41
    206: 11
    207: 28
    208: 3
    209: 119
    210: 11
    211: 5
    212: 7
    213: 36
    215: 9
    216: 55
    217: 6
    218: 18
    220: 47
    221: 1
    223: 4
    224: 27
    227: 26
    230: 31
    231: 1
    233: 8
    234: 6
    235: 13

---

spring:
  profiles: test

server:
  port: 8082
defaults:
  delaySubmission: false
  topHandCount: 20
  bottomHandCount: 10
  maxAllotedTimeForRequest: 30
